config/routes.rb
RssReaderExample::Application.routes.draw do
  resources :feeds do
    resources :posts
  end
  

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users
  resources :users


end

app/models/feed.rb
require 'feedzirra'

class Feed < ActiveRecord::Base
  after_create :fetch_posts
  attr_accessible :title, :url

  validates :url, :uniqueness => true, :presence => true

  has_many :posts, :dependent => :destroy

  def fetch_posts
    feed = Feedzirra::Feed.fetch_and_parse(self.url)
    self.title = feed.title

    recently_fetched = self.posts.first(20)
    feed.entries.first(10).each do |entry|
      # strip tags from preview
      summary = entry.summary || "No summary was provided by the feed."
      post = Post.new(:preview => summary.gsub( %r{</?[^>]+?>}, '' ), :author => entry.author || "...someone", :content => entry.content, :title => entry.title, :url => entry.url)
      post.feed = self
      # only attempt to save if the post is not part of what I already have
      post.save if recently_fetched.select {|rec| rec.url == post.url}.count == 0
    end
    self.save
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.includes(:posts).find(params[:id])
    @feed.fetch_posts
    @feed.posts.sort_by {|p| p.published_date}

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        @feed.fetch_posts
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= simple_form_for(@feed) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.title %></td>
    <td><%= link_to 'Show', feed, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<%= content_for :head do %>
  <script>
    $(document).ready(function() {
      $('.post').tooltip();
    });
  </script>
<% end %>

<p>
  <b>Feed Title:</b>
  <%= @feed.title %>
</p>

<p>Hover over links for a preview.</p>

<div id="posts">
  <% @feed.posts.each do |post| %>

  <div>
    <span class='post' data-toggle="tooltip" data-placement="top" title="<%= post.preview %>">
      <%= link_to raw(post.title), "/feeds/#{post.feed_id}/posts/#{post.id}", :remote=>true, :data => {:toggle=>"modal", :target=>"#modal"} %>
      <span class="author"> by <%= post.author %></span>
    </span>
  </div>

  <% end %>
</div>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>


<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div id="modal-header" class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Modal header</h3>
  </div>
  <div id="modal-body" class="modal-body">
    <p>Static content...</p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>